### ISSUE TITLE
anchors not working with table driven tests / multiple t.Cmp calls

### ISSUE THREAD

**Issue by derekperkins** [maxatome/go-testdeep#191]
I'm building some Stripe tests with large, deeply nested structs, where using anchors is very helpful. They work great when I have a single test, but if I'm calling `t.Cmp` multiple times or have table driven tests, anchors are being compared against the wrong values. Since the anchors have to be set outside the inner test run loop, I'm not sure how `td` knows when to iterate between them. Am I doing something incorrectly?

#### Table driven test
```go
func Test_payInvoiceWithStripe(stdT *testing.T) {
	tdt := td.NewT(stdT)

	tests := []struct {
		name                  string
		stripeCustomerID      string
		stripePaymentMethodID string
		wantPaymentIntent     *stripe.PaymentIntent
		wantErr               error
	}{
		// lots of tdt.A
	}

	stripeClient := client.New(apiKey, nil)
	invoice := &billingpb.Invoice{
		InvoiceId:            111,
		AccountId:            22222,
	}

	for i, tt := range tests {
		tdt.Run(tt.name, func(t *td.T) {
			gotPaymentIntent, err := chargeCustomer(context.Background(), stripeClient, tt.stripeCustomerID, tt.stripePaymentMethodID, invoice, int64(i))
			if tt.wantErr == nil {
				t.CmpNoError(err)
			} else {
				t.Cmp(e.Cause(err).(*stripe.Error), e.Cause(tt.wantErr).(*stripe.Error))
			}
			t.Cmp(gotPaymentIntent, tt.wantPaymentIntent)
		})
	}
```

#### Output
```
        DATA.ChargeID: values differ
        	     got: "ch_3KH0DO4HQ2O7mN7V1o3cxNfi"
        	expected: "<testdeep@anchor#12>"
```

Thanks for a great library!

**Comment by maxatome** [comment]
Hi @derekperkins and happy new year !

Anchors are only valid for the next `Cmp` call to avoid filling memory uselessly.

But, if you want they persist, you can call [`AnchorsPersistTemporarily`](https://pkg.go.dev/github.com/maxatome/go-testdeep/td#T.AnchorsPersistTemporarily) as in https://go.dev/play/p/8qmvkWMhtxi

This way, the cleaning of anchors is delayed until cleanup and so all registered anchors are usable by all following `Cmp` calls.

As you can see in the playground example, it works even in your sub-test case because when [`Run`](https://pkg.go.dev/github.com/maxatome/go-testdeep/td#T.Run) is called, the registered anchors are inherited.

**Comment by derekperkins** [comment]
That worked great, thanks for the heads up @maxatome!
